go:
  lintTool: golangci-lint
  lintFlags:
    - "--fast"

linters:
  disable:
    - scripts/cmd/**
    - scripts/distelledPrompts/**

linters-settings:
  govet:
    disable-all: false
    disable:
      - loopclosure

